// Copyright 2017-2025 Razer, Inc. All Rights Reserved.

#include "SampleGameWyvrnBP.h" //___HACK_UE4_VERSION_4_16_OR_GREATER
#include "Wyvrn_Sample.h"
//#include "SampleGameWyvrnBP.h" //___HACK_UE4_VERSION_4_15_OR_LESS
#include "WyvrnSDKPluginBPLibrary.h"
#include "WyvrnErrors.h"


DEFINE_LOG_CATEGORY(LogWyvrnSampleGame);


//USampleGameWyvrnBP::USampleGameWyvrnBP(const FPostConstructInitializeProperties& PCIP) //___HACK_UE4_VERSION_4_8_OR_LESS
//	: Super(PCIP) //___HACK_UE4_VERSION_4_8_OR_LESS
USampleGameWyvrnBP::USampleGameWyvrnBP(const FObjectInitializer& ObjectInitializer) //___HACK_UE4_VERSION_4_9_OR_GREATER
	: Super(ObjectInitializer) //___HACK_UE4_VERSION_4_9_OR_GREATER
{
}

void USampleGameWyvrnBP::SampleGameSampleStart()
{
#if PLATFORM_WINDOWS || (defined(PLATFORM_XBOXONE) && PLATFORM_XBOXONE)
	if (!UWyvrnSDKPluginBPLibrary::IsInitialized())
	{
		FWyvrnSDKAppInfoType appInfo;
		appInfo.Title = "Game Sample: Application";
		appInfo.Description = "A sample application using Razer Wyvrn SDK";
		appInfo.Author_Name = "Razer";
		appInfo.Author_Contact = "https://wyvrn.com";

		//    0x01 | // Utility. (To specifiy this is an utility application)
		//    0x02   // Game. (To specifiy this is a game);
		appInfo.Category = 1;

		int32 result = UWyvrnSDKPluginBPLibrary::WyvrnSDKInitSDK(appInfo);
		switch (result)
		{
		case RZRESULT_DLL_NOT_FOUND:
			UE_LOG(LogWyvrnSampleGame, Log, TEXT("WyvrnSDK DLL is not found!"));
			break;
		case RZRESULT_DLL_INVALID_SIGNATURE:
			UE_LOG(LogWyvrnSampleGame, Log, TEXT("WyvrnSDK DLL has an invalid signature!"));
			break;
		case RZRESULT_SUCCESS:
			//UE_LOG(LogWyvrnSampleGame, Log, TEXT("WyvrnSDK has initialized successfully!"));
			break;
		default:
			// It's not an error for WyvrnSDK to not initialize.
			// The SDK might not be installed.
			// Just avoid making further calls to WyvrnSDK until next launch.
			UE_LOG(LogWyvrnSampleGame, Log, TEXT("Failed to initialize WyvrnSDK!"));
			break;
		}
	}
#elif defined(PLATFORM_PS5) && PLATFORM_PS5
	if (!UWyvrnSDKPluginBPLibrary::IsInitialized())
	{
		// PS5 brings up HAR + the DualSense provider through the plugin's
		// Interhaptics backend; the Razer app info is unused there.
		FWyvrnSDKAppInfoType AppInfo;
		const int32 Result = UWyvrnSDKPluginBPLibrary::WyvrnSDKInitSDK(AppInfo);
		UE_LOG(LogWyvrnSampleGame, Log, TEXT("WyvrnSDK PS5 init result: %d"), Result);
	}
#endif
}

void USampleGameWyvrnBP::SampleGameSampleEnd()
{
#if PLATFORM_WINDOWS || (defined(PLATFORM_XBOXONE) && PLATFORM_XBOXONE) || (defined(PLATFORM_PS5) && PLATFORM_PS5)
	UWyvrnSDKPluginBPLibrary::WyvrnSDKUnInit();
#endif
}
#pragma region Autogenerated

void USampleGameWyvrnBP::SampleGameShowEffect1()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect1");
}

void USampleGameWyvrnBP::SampleGameShowEffect2()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect2");
}

void USampleGameWyvrnBP::SampleGameShowEffect3()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect3");
}

void USampleGameWyvrnBP::SampleGameShowEffect4()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect4");
}

void USampleGameWyvrnBP::SampleGameShowEffect5()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect5");
}

void USampleGameWyvrnBP::SampleGameShowEffect6()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect6");
}

void USampleGameWyvrnBP::SampleGameShowEffect7()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect7");
}

void USampleGameWyvrnBP::SampleGameShowEffect8()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect8");
}

void USampleGameWyvrnBP::SampleGameShowEffect9()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect9");
}

void USampleGameWyvrnBP::SampleGameShowEffect10()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect10");
}

void USampleGameWyvrnBP::SampleGameShowEffect11()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect11");
}

void USampleGameWyvrnBP::SampleGameShowEffect12()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect12");
}

void USampleGameWyvrnBP::SampleGameShowEffect13()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect13");
}

void USampleGameWyvrnBP::SampleGameShowEffect14()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect14");
}

void USampleGameWyvrnBP::SampleGameShowEffect15()
{
	// Trigger AI, Chroma, and haptics
	UWyvrnSDKPluginBPLibrary::SetEventName("Effect15");
}

#pragma endregion

#pragma region PS5 Haptics Debug Harness

// These mirror the Debug_* commands authored in the debug WYVRN.config. They
// drive the PS5 haptics backend exactly as a game would (SetEventName), so the
// transcode-to-Interhaptics behaviour can be felt on a DualSense.

void USampleGameWyvrnBP::SampleGameDebugLoopA()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_LoopA");
}

void USampleGameWyvrnBP::SampleGameDebugLoopB()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_LoopB");
}

void USampleGameWyvrnBP::SampleGameDebugStopA()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_StopA");
}

void USampleGameWyvrnBP::SampleGameDebugStopAll()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_StopAll");
}

void USampleGameWyvrnBP::SampleGameDebugHandGlobal()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_HandGlobal");
}

void USampleGameWyvrnBP::SampleGameDebugHandLeft()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_HandLeft");
}

void USampleGameWyvrnBP::SampleGameDebugHandRight()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_HandRight");
}

void USampleGameWyvrnBP::SampleGameDebugPriorityLow()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_PriorityLow");
}

void USampleGameWyvrnBP::SampleGameDebugPriorityHigh()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_PriorityHigh");
}

void USampleGameWyvrnBP::SampleGameDebugEqualA()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_EqualA");
}

void USampleGameWyvrnBP::SampleGameDebugMergeB()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_MergeB");
}

void USampleGameWyvrnBP::SampleGameDebugOverrideB()
{
	UWyvrnSDKPluginBPLibrary::SetEventName("Debug_OverrideB");
}

#pragma endregion
